#Config - Updated 10/04/2019

#Currenly working
cloud:

config:


http:
  api_password: admin

system_health:


#May be correct usage, cannot test as of yet.
person:
  - name: Bolians
    id: 0e451b3ad26042a49fa7150252e930da
    device_trackers:
      - device_tracker.Bolians


asuswrt:
  host: 192.168.1.1
  username: admin  
  password: hotelquaint712
  protocol: telnet
  port: 23
device_tracker:
  - platform: asuswrt
    interval_seconds: 20
    consider_home: 180
    new_device_defaults:
      track_new_devices: true

#Cannot test as of yet
media_player:
  - platform: soundtouch
    host: 192.168.1.1
    port: 8090
    name: Soundtouch Living Room
